# Project: xox
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/rusk_rask/d/Dev-Cpp11/MinGW64/lib" -L"D:/rusk_rask/d/Dev-Cpp11/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -fno-elide-constructors
INCS     = -I"D:/rusk_rask/d/Dev-Cpp11/MinGW64/include" -I"D:/rusk_rask/d/Dev-Cpp11/MinGW64/x86_64-w64-mingw32/include" -I"D:/rusk_rask/d/Dev-Cpp11/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/rusk_rask/d/Dev-Cpp11/MinGW64/include" -I"D:/rusk_rask/d/Dev-Cpp11/MinGW64/x86_64-w64-mingw32/include" -I"D:/rusk_rask/d/Dev-Cpp11/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/rusk_rask/d/Dev-Cpp11/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = xox.exe
CXXFLAGS = $(CXXINCS) -std=c++14 -pthread -fno-elide-constructors
CFLAGS   = $(INCS) -std=c++14 -pthread -fno-elide-constructors
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
